### ISSUE TITLE
Error running 0.12.90

### ISSUE THREAD

**Issue by mvndrstl** [overviewer/Minecraft-Overviewer#1275]
I get the following error after updating to 0.12.90. It worked fine on 0.12.87. Minecraft version is 1.8.9 and OS is CentOS 6 if that matters.

Command:
`VANILLA_WORLD="/home/mark/vanillaMinecraft/world" overviewer.py --config=/home/mark/mcmaps/overviewer.config --genpoi --skip-scan`

Output:
```
2016-02-09 13:19:00 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 605, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 130, in main
    g.genPOI.main()
  File "/usr/lib64/python2.6/site-packages/overviewer_core/aux_files/genPOI.py", line 514, in main
    PlayerDict.load_cache(destdir)
  File "/usr/lib64/python2.6/site-packages/overviewer_core/aux_files/genPOI.py", line 216, in load_cache
    with gzip.GzipFile(cache_file) as gz:
AttributeError: GzipFile instance has no attribute '__exit__'
```

Config file:
```
import os

worlds['Vanilla'] = os.environ['VANILLA_WORLD']

def playerLocations(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "http://minotar.net/avatar/%s/32" % poi['EntityId']
        return "Current location for %s" % poi['EntityId']

def playerSpawns(poi):
    if poi['id'] == 'PlayerSpawn':
        poi['icon'] = "http://minotar.net/avatar/%s/32" % poi['EntityId']
        return "Spawn location for %s" % poi['EntityId']

def locations(poi):
    if poi['id'] == 'Location':
        return poi['name']

renders["vanillaOverworldDay"] = {
    'world': 'Vanilla',
    'title': 'Overworld Day',
    'rendermode': [Base(), EdgeLines(), SmoothLighting(strength=0.5)],
    'dimension': 'overworld',
    'northdirection': 'upper-right',
    'manualpois':[
                  {'id':'Location',
                   'x':-234,
                   'y':70,
                   'z':-700,
                   'name':'Aroughs'}
                 ],
    'markers': [dict(name="Locations", filterFunction=locations, createInfoWindow=False),
                dict(name="Players", filterFunction=playerLocations, createInfoWindow=False),
                dict(name="Player Spawn Points", filterFunction=playerSpawns, createInfoWindow=False)],
}

renders["vanillaOverworldNight"] = {
    'world': 'Vanilla',
    'title': 'Overworld Night',
    'rendermode': [Base(), EdgeLines(), SmoothLighting(night=True, strength=0.8)],
    'dimension': 'overworld',
    'northdirection': 'upper-right',
}

renders["vanillaNether"] = {
    'world': 'Vanilla',
    'title': 'Nether',
    'rendermode': [Base(), EdgeLines(), Nether(), SmoothLighting(strength=0.4)],
    'dimension': 'nether',
    'northdirection': 'upper-right',
}

outputdir = "/home/mark/mcmaps"
texturepath = "/home/mark/mcmaps/faithful32pack.zip"
processes = 3
```

**Comment by CounterPillow** [comment]
That one is probably my fault. I'll look into it soon.

**Comment by CounterPillow** [comment]
Should be fixed in 4e77ba8, thanks for reporting this.

**Comment by mvndrstl** [comment]
Can confirm was fixed in 0.12.91. Thanks!
